name: Build Linux

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      
jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install sudo package
        run: apt update && apt install sudo
      - name: Install libpng
        run: |
          sudo apt-get install libpng-dev -y
      - name: Build Linux framework
        run: |
           swift build
           swift test
      - name: Build Linux Demo
        run: |
            cd Demo/Demo\ Ubuntu
            swift build
